---
- name: Swap disabling
  ansible.builtin.include_tasks:
    file: "swap-disable.yml"

- name: Setup kernel
  ansible.builtin.include_tasks:
    file: "kernel-setup.yml"

# # https://github.com/containerd/containerd/blob/main/docs/getting-started.md


# DONE
#   # 1) нужно включить tcp forwarding
#редактирование файла /etc/sysctl.d/99-sysctl.conf

# подгрузить модуль ядра 
# sudo modprobe nf_conntrack
# добавить файл /etc/modules-load.d/nf_conntrack.conf с содержимым nf_conntrack
  




#   # 2) для загрузки containerd переменная лежит в group_vars
#   # wget https://github.com/containerd/containerd/releases/download/v2.2.2/containerd-2.2.2-linux-amd64.tar.gz
#   # для распаковки 
#   # tar Cxzvf /usr/local containerd-1.6.2-linux-amd64.tar.gz
#   # скачать containerd.service для systemd https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
# #   и положить в папку с unit   /usr/local/lib/systemd/system/containerd.service
# # sudo curl -o /etc/systemd/system/containerd.service https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
# #   перезагрузить демон
# #   systemctl daemon-reload
# # systemctl enable --now containerd

# # 3)
# # загрузка runс с переменной runc_version и архитектурой
# # sudo curl -o /usr/local/sbin/runc https://github.com/opencontainers/runc/releases/download/v1.5.0-rc.2/runc.amd64
# # изменить права на 755 и chmod +x
  
#   4) установка cni плагинов

#   добавить переменную cni плагинов
  
#   создание папки mkdir -p /opt/cni/bin
#   загрузка cni плагинов
#   wget https://github.com/containernetworking/plugins/releases/download/v1.9.1/cni-plugins-linux-amd64-v1.9.1.tgz
#   распаковка плагинов в папку
#   tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v1.1.1.tgz


# 5) сделать конфиг

# сделать папку /etc/containerd

# собрать конфиг containerd 
# containerd config default | sudo tee /etc/containerd/config.toml
# включить SystemdGroup на тру

# 6) установка kubectl
# https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management

# или установка всех компонентов в сумме
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl