---
- name: Setup SSH on hosts
  hosts: all
  vars:
    sshd_config: "/etc/ssh/sshd_config"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=accept-new"
  gather_facts: false

  handlers:
    - name: Restart ssh daemon through systemd
      become: true
      ansible.builtin.systemd_service:
        name: ssh
        state: restarted

  tasks:
    # COPY SSH PUBLIC KEYS BLOCK
    - name: Get host keys to from inventory
      delegate_to: localhost
      shell: "ssh-keyscan -t rsa {{ ansible_host }}"
      register: host_keys
      ignore_unreachable: true
    
    - name: Add host keys to known_hosts
      delegate_to: localhost
      known_hosts: 
        name: "{{ ansible_host }}"
        key: "{{ host_keys.stdout }}"
        state: present
      ignore_unreachable: true

    - name: Search public keys on localhost
      delegate_to: localhost
      ansible.builtin.find:
        paths: "{{ lookup('env', 'HOME') }}/.ssh/"
        patterns: "id_*.pub"
      register: keys_paths
      
    - name: Check for key exists
      ansible.builtin.assert:
        that: keys_paths.matched > 0
        fail_msg: "Error! Can't find public keys in users .ssh folder!"
        success_msg: "Public keys found. OK!"

    - name: Gather facts from host
      ansible.builtin.setup:
        
    - name: Distribute ansible user ssh key to hosts
      ansible.posix.authorized_key:
        state: present
        comment: "{{ ansible_user_id }}_user_automate_ssh_key_distribution_"
        exclusive: false
        user: "{{ lookup('env', 'USER') }}"
        key: "{{ lookup('file', item) }}"
      loop: "{{ keys_paths.files | map(attribute='path') }}"

    #SETUP SSH CONFIG BLOCK
    - name: Find custom sshd_config file
      ansible.builtin.find:
        paths: "{{ sshd_config }}.d/"
        patterns: "*.conf"
      register: sshd_config_files

    - name: Remove custom sshd_config_files
      become: true
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop: "{{ sshd_config_files.files | map(attribute='path') }}"

    - name: Disable root login
      become: true
      ansible.builtin.replace:
        path: "{{ sshd_config }}"
        regexp: "^.*PermitRootLogin.*$"
        replace: "PermitRootLogin no"
      notify: 'Restart ssh daemon through systemd'
    
    - name: Disable password entry function
      become: true
      ansible.builtin.replace:
        path: "{{ sshd_config }}"
        regexp: "^.*PasswordAuthentication.*$"
        replace: "PasswordAuthentication no"
      notify: 'Restart ssh daemon through systemd'

    - name: Disable sudo password for current user
      become: true
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ lookup('env', 'USER') }}"
        content: "{{ lookup('env', 'USER') }}    ALL=(ALL:ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: '0440'
