---
vars_type: "default"

packages:
  - nano
  - iputils-arping
  - iputils-clockdiff
  - iputils-ping
  - iputils-tracepath
  - curl
  - wget
  - smartmontools
  - htop
  - nfs-common
  - make
  - gcc
  - linux-libc-dev
  - libseccomp-de
  - pkg-config
  - git
  - apt-transport-https
  - ca-certificates
  - gnupg
